---
#title: "Información sobre el curso"
toc: true
#self-contained: true
toc-title-website: "En esta página"
toc-title-document: "Indice de contenidos"

---

## Trabajos (curso 2025-26)


Los  estudiantes del **curso 2025-2026**, como parte de la evaluación continua, tuvieron que presentar dos trabajos, uno individual y otro en equipo. Puedes verlos en los siguientes enlaces:



### Trabajos en equipo

<br>

-  **Simón Casañ Olmos** , **Adrián Fernández Bruque** y **Carlos Hueso Muñoz** Realizaron el trabajo: [Champions League](https://Adrifer04.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/Adrifer04/trabajo_BigData){target="_blank"}. 

<br>

-   **Rayan Akhnati Tafar**, **Noura Es Salhi Piquer** y **Giulia Piovesan** presentaron el trabajo [La evolución del aborto en las últimas décadas](https://nuraesp.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/nuraesp/trabajo_BigData){target="_blank"}.

<br>


-   **Gabriela Galeano**, **Arantxa Arcos** y **Lucía Bellido** presentaron el trabajo [Homicidios por el Mundo](https://gabagaleano/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/gabagaleano/trabajo_BigData_equipo){target="_blank"}.



## Cursos anteriores

<br>

::: {.callout-note collapse="false" appearance="default" icon="false"}
#### Trabajos de cursos anteriores


Puedes ver los trabajos elaborados por estudiantes de **cursos anteriores** en los siguiente links:

   - [Curso 2024-25](./mas-cosas/07-trabajos_2024-25.html){target="_blank"}

   - [Curso 2023-24](./mas-cosas/07-trabajos_2023-24.html){target="_blank"}

   - [Curso 2022-23](./mas-cosas/07-trabajos_2022-23.html){target="_blank"}
   
   - [Curso 2021-22](./mas-cosas/07-trabajos_2021-22.html){target="_blank"}
   
   - [Curso 2020-21](./mas-cosas/07-trabajos_2020-21.html){target="_blank"}
   
   - [Curso 2019-20](./mas-cosas/07-trabajos_2019-20.html){target="_blank"}

:::

