---
output:
  html_document:
    #css: !expr here::here("assets", "styles_pjp.css") 
    #css: assets/styles_pjp.css
    theme: united #cerulean  #o flatly(gris)  united (naranja) spacelab(azulito) o yeti o faltly o sandstone
    #highlight: kate 
    self_contained: yes
    number_sections: no
    #includes:
       #in_header: google-analytics.html
    toc: true
    toc_float: true
    #code_folding: show
    #self_contained: TRUE
---

<br>

<br>

# Curso 2022-2023

<br>

::: blue
**Trabajos**: los 28 estudiantes del **curso 2022-2023**, como parte de la evaluación continua, tuvieron que presentar dos trabajos, uno individual y otro en equipo. Podrás verlos en los siguientes enlaces:
:::

<br><br>

## Trabajos en equipo

<br>

-   **Naira Carruccio Villada**, **Alex Monzó Santana** y **Luis Antonio Pérez Padauy** presentaron el trabajo [La evolución del gasto en educación en España y su relación con las pruebas PISA](https://AlexMS77.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/AlexMS77/trabajo_BigData_equipo){target="_blank"}.

<br>

-   **Helena Albors**, **Noelia Teruel** y **Carla Morgado** presentaron el trabajo [El papel de la mujer en la educación y en el trabajo](https://carlam01.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/carlam01/trabajo_BigData_equipo){target="_blank"}.

<br>

-   **Paula Martínez Serrano**, **Sonia Monleón Fernández** y **Leire Montón Pastor** presentaron el trabajo [Evolución del mercado laboral en España](https://Soniamf.github.io/trabajo_bigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/Soniamf/trabajo_bigData_equipo){target="_blank"}.

<br>

-   **Alejandro Hortelano Martín** , **Víctor Gallego Urrea** y **José María Perez** presentaron el trabajo [Big Data en la Formula 1](https://alexhortelano6.github.io/Big-Data-en-la-Formula-1/) El repo del trabajo está [aquí](https://github.com/alexhortelano6/Big-Data-en-la-Formula-1.git){target="_blank"}.

<br>

-   **Josep Gómez Corral**, **Ferran Alemany Parets** y **Rubén Rodríguez Giménez** presentaron el trabajo [Infraestructuras ferroviarias en Europa: El problema de España.](https://roodrigueezzz.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/roodrigueezzz/trabajo_BigData_equipo){target="_blank"}.

<br>

-   **Yi Zhang**, **Raphaëlle Bastien** y **Kaikai Qiu** presentaron el trabajo [Análisis económico sobre la crisis de la pandemia](https://yiz2001.github.io/trabajo_Bigdata_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/yiz2001/trabajo_BigData_equipo){target="_blank"}.

<br>

-   **Ignacio Manuel Muñoz Ayala**, **María Mena Esteban** y **Miguel Herrero Fuertes** presentaron el trabajo [Inflación en tiempos de pandemia](https://ignacioman.github.io/trabajo_BigData_equipo/las_slides_estan.html){target="_blank"}. El repo del trabajo está [aquí](https://github.com/IgnacioMan/trabajo_BigData_equipo){target="_blank"}.

<br>

-   **Carlos Garcia Ponce** y **Vera Monteagudo Serrano** presentaron el trabajo [Estudio de las plataformas audiovisuales](https://Carlos596.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/Carlos596/trabajo_BigData_equipo){target="_blank"}.

<br>

-   **Sukhman Kaur**, **Juliet Allegra** y **Juan David** presentaron el trabajo [Streaming vs. Cine](https://kaursukhman.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/kaursukhman/trabajo_BigData_equipo){target="_blank"}.

<br>

-   **Adeline Baillifard**, **Lena Baerwinkel** y **Luis Steven Vega** presentaron el trabajo [Las energías en Europa](https://Baillifa10.github.io/trabajo_BigData_equipo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/Baillifa10/trabajo_BigData_equipo){target="_blank"}.

<br>

-   **Sandra March Arazola**, **Alberto Cabrera Pérez** y **Alegría Pintado Barcelo** presentaron el trabajo [Incertidumbre por la escalada de precios](https://alcape4.github.io/trabajo_BigData_grupo/my_trabajo_BigData.html){target="_blank"}. El repo del trabajo está [aquí](https://github.com/alcape4/trabajo_BigData_grupo){target="_blank"}.

<br><br>

## Trabajos individuales

<br>

-   **Josep Gómez Corral** presentó el trabajo [2005 y 2006. Las dos del Nano](https://gomezz01.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/gomezz01/trabajo_BigData){target="_blank"}.

-   **Alejandro Hortelano Martín** presentó el trabajo [Levante UD en la temporada 18-19](https://alexhortelano6.github.io/Levante-UD-en-la-temporada-18-19/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/alexhortelano6/Levante-UD-en-la-temporada-18-19){target="_blank"}.

-   **Rubén Rodríguez Giménez** presentó el trabajo [Mercado de coches de segunda mano](https://roodrigueezzz.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/roodrigueezzz/trabajo_BigData){target="_blank"}.

-   **Alex Monzo Santana** presentó el trabajo [La mejor serie: The Walking Dead](https://AlexMS77.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/AlexMS77/trabajo_BigData/){target="_blank"}.

-   **María Mena Estebán** presentó el trabajo [El desempleo y las carreras universitarias en España](https://mmena21.github.io/desempleo_y_carreras_universitarias/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/mmena21/desempleo_y_carreras_universitarias/){target="_blank"}.

-   **Luis Pérez** presentó el trabajo [Deuda Soberana Estadounidense](https://padauy.github.io/Trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/padauy/Trabajo_BigData){target="_blank"}.

-   **Adeline Baillifard** presentó el trabajo [Las páginas web más visitadas](https://Baillifa10.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/Baillifa10/trabajo_BigData){target="_blank"}.

-   **Sukhman Kaur** presentó el trabajo [Análisis y trayectoria económica de India](https://kaursukhman.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/kaursukhman/trabajo_BigData){target="_blank"}.

-   **Kaikai Qiu** presentó el trabajo [La lotería de Navidad](https://alonsoqiu.github.io/my_trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/Alonsoqiu/my_trabajo_BigData){target="_blank"}.

-   **Paula Martínez Serrano** presentó el trabajo [Violencia de género en España](https://paumars3.github.io/trabajo_individual/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/Paumars3/trabajo_individual){target="_blank"}.

-   **Víctor Gallego Urrea** presentó el trabajo [Big Data en la Euroliga - ACB](https://vicgau01.github.io/Trabajo_individual_V-ctor_Gallego_NBAyEuroliga_en_BigData/){target="_blank"}. La repo del trabajo está [aquí](https://github.com/vicgau01/Trabajo_individual_V-ctor_Gallego_NBAyEuroliga_en_BigData){target="_blank"}.

-   **Helena Albors** presentó el trabajo [Indicadores que afectan al nivel de desarrollo de los países](https://helenaalbors.github.io/my_trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/helenaalbors/my_trabajo_BigData){target="_blank"}.

-   **Carla Morgado** presentó el trabajo [La evolución de los sectores económicos](https://carlam01.github.io/trabajo_BigData/){target="_blank"}.El repo del trabajo está [aquí](https://github.com/carlam01/trabajo_BigData){target="_blank"}.

-   **Juan Emilio Gómez-Meana Torres** presentó el trabajo [El potencial económico de Brasil](https://egomez22.github.io/Trabajo_individual_bigdata/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/egomez22/Trabajo_individual_bigdata){target="_blank"}.

-   **Naira Carruccio Villada** presentó el trabajo [Análisis de la plataforma de Filmaffinity](https://carru8.github.io/trabajo_BigData/){target="_blank"}.El repo del trabajo está [aquí](https://github.com/carru8/trabajo_BigData){target="_blank"}.

-   **Yi Zhang** presentó el trabajo [El Ramen mola](https://yiz2001.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/yiz2001/trabajo_BigData){target="_blank"}.

-   **Sonia Monleón Fernández** presento el trabajo [Inversión en protección medio ambiental](https://soniamf.github.io/trabajo_individual_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/soniamf/trabajo_individual_BigData){target="_blank"}.

-   **Vera Monteagudo** presentó el trabajo [La felicidad en relación a la renta](https://vemonse.github.io/BigData_trabajo/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/vemonse/BigData_trabajo){target="_blank"}.

-   **Javier Ruiz Puchol** presentó el trabajo [Análisis de la Industria Musical: Spotify](https://jarupu.github.io/trabajo-Bigdata/). El repo del trabajo está [aquí](https://github.com/jarupu/Trabajo-Bigdata).

-   **Raphaelle Bastien** presentó el trabajo [Análisis de la Industria Musical: Spotify](https://RaphaelleBastien.github.io/trabajo-Bigdata/). El repo del trabajo está [aquí](https://github.com/RaphaelleBastien/trabajo_BigData).

-   **Alberto Cabrera Pérez** presentó el trabajo [Evolución de la esperanza de vida](https://alcape4.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/alcape4/trabajo_BigData){target="_blank"}.

-   **Ignacio Manuel Muñoz Ayala** presentó el trabajo [Temporada 2020-2021 F1](https://ignacioman.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/ignacioman/trabajo_BigData).

-   **Leire Montón** presentó el trabajo [Nombres de hombres y mujeres en España](https://leiremonton.github.io/trabajo_leire/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/leiremonton/trabajo_leire){target="_blank"}.

-   **Noelia Teruel Ortega** presentó el trabajo [Rosalía y C. Tangana en Spotify](https://noeliateruel.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/noeliateruel/trabajo_BigData){target="_blank"}.

-   **Sandra March Arazola** presentó el trabajo [Debates de actualidad](https://marcharazola.github.io/Trabajo-individual-Big-Data/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/MarchArazola/Trabajo-individual-Big-Data){target="_blank"}.

-   **Alegría Pintado Barceló** presento el trabajo [Argumentos que defienden la existencia del salario mínimo](https://alegriapb.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/AlegriaPB/trabajo_BigData){target="_blank"}.

-   **Victor Muñoz Barrasa** presentó el trabajo [Liga BBVA](https://victormunozz.github.io/trabajo_bigdata_individual/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/victormunozz/trabajo_bigdata_individual){target="_blank"}.

-   **Miguel Herrero Fuertes** presentó el trabajo trabajo [Análisis del paro en España](https://miguelhf42.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/miguelhf42/trabajo_BigData){target="_blank"}

-   **Carlos García Ponce** presentó el trabajo [Fútbol internacional](https://Carlos596.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/Carlos596/trabajo_BigData){target="_blank"}.

-   **Juliet Allegra** presentó el trabajo [Best Selling Music Artists](https://julucape.github.io/Best-Selling-Music-Artists/posts/post-with-code/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/julucape/Best-Selling-Music-Artists){target="_blank"}.

-   **Lena Baerwinkel** presentó el trabajo [La exploración de las series más populares de Netflix](https://lena-marie-999.github.io/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/LENA-MARIE-999/LENA-MARIE-999.github.io){target="_blank"}.

-   **Juan Rios** presentó el trabajo [Comparación importantes métricas entre países europeos](https://juandavidriosm.github.io/Comparaci-n-importantes-m-tricas-entre-pa-ses-europeos/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/juandavidriosm/Comparaci-n-importantes-m-tricas-entre-pa-ses-europeos){target="_blank"}.

<br><br>

------------------------------------------------------------------------

::: {.tocify-extend-page data-unique="tocify-extend-page" style="height: 0;"}
:::
