---
title: "Entrega de trabajos individuales"
format:
  html:
    theme: simplex #- minty zephyr yeti vapor united superhero(ok) solar (ok) slate sketchy simplex sandstone quartz pulse morph materia lux journal darkly cyborg cerulean     
    toc: true
    toc-location: left
    link-external-newwindow: true
embed-resources: true
fig-cap-location: top
code-line-numbers: false
---


```{r, include = FALSE}
library(tidyverse)
```
  
<br>

## 1. Subiendo los trabajos a Github

- Se han de subir a Github **después de que el trabajo esté completamente acabado** 

- Bosquejo del proceso:

    - Entráis a Github con vuestro usuario y contraseña

    - Crear un nuevo repo: `NEW` . Hay que ponerle **exactamente** el nombre `trabajo_BigData` 

    - Vais subiendo los archivos (con `upload file`). Solo se pueden subir 100 archivos cada vez

    - Finalmente hay que hacer que se pueda visualizar el trabajo en internet. Para ello hay que ir al repo de tu trabajo. Una vez allí, hay que ir a `Settings` y en la parte de abajo hay una sección que se llama `Pages`. Allí encontrarás una sección lalmada "Build and deployment". En esta sección hay que seleccionar `main` y `/root`  y darle a `Save`. En unos minutos el trabajo estará visible en internet en al dirección: `https://<tu-usuario-Github>.github.io/trabajo_BigData/`; por ejemplo, en mi caso, que mi usuario es `perezp44`, mi dirección sería: `https://perezp44.github.io/trabajo_BigData/`
    
    

<br>

## 2. Para finalizar el trabajo individual


- Una vez este el trabajo finalizado y visible en internet **tenéis que mandarme un mail** avisándome. 

- La fecha límite de entrega será el **miércoles 7 de enero** a las 23:59

- El mail **tiene que ser** algo como:


```{yaml}
Asunto: BigData - trabajo - Nerea Pérez Mártinez

Hola Pedro,
soy Nerea Pérez Mártinez

El título del trabajo es: Una aproximación empírica a los problemas económicos más tochos

Mi usuario de Github es: nereaPM_99

Por lo tanto, el párrafo que has de poner en la web de la asignatura para que puedas poner el enlace a nuestro trabajo es exactamente este:


-   **Nerea Pérez Mártinez** presentó el trabajo [Una aproximación empírica a los problemas económicos más tochos](https://nereaPM_99.github.io/trabajo_BigData/){target="_blank"}. El repo del trabajo está [aquí](https://github.com/nereaPM_99/trabajo_BigData){target="_blank"}.

Pedro, he tenido mucho cuidado en cambiar el nombre de los integrantes del equipo, el título del trabajo y el usuario de Github en 2 sitios, así que debería funcionar tal cual.

Saludos

PD: Genial, lo HE conseguido!!! ✅ 😊

```

